module.exports = {
  RESET: 'RESET',
  MOVE_TO: 'MOVE_TO',
  PUSH_DOZER: 'PUSH_DOZER',
  IDLE_DOZER: 'IDLE_DOZER',
  PREPARE_DOZER: 'PREPARE_DOZER',
  SET_SETTINGS: 'SET_SETTINGS',
  GET_SETTINGS: 'GET_SETTINGS',
  GET_STATUS: 'GET_STATUS',
}
